name: postgres
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db
    volumes:
      - ./temp/scripts:/docker-entrypoint-initdb.d