server:
  servlet:
    context-path: "/product-app"
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/my_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        connection:
          driver_class: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none